'use client'

import '@radix-ui/themes/styles.css'

import '../globals.css'
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import { AccountFormProvider } from '../context/AccountFormContext'
import { AuthContextProvider } from '../context/AuthContext'
import { ToastProvider } from '@radix-ui/react-toast'
import { Toaster } from '@/components/ui/Toaster'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Turborepo',
//   description: 'Generated by create turbo',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <AccountFormProvider>
            <Theme>
              <ToastProvider>{children}</ToastProvider>
              <Toaster />
            </Theme>
          </AccountFormProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
